export const pageData = {
  '/': {
    label: 'Home',
    title: 'Frame Syndicate | Software, Cloud, AI & SEO Solutions',
    description: 'Frame Syndicate designs and builds software, cloud, cybersecurity, AI, and SEO solutions for growing businesses in Nepal and beyond.',
    author: 'Frame Syndicate editorial team',
    updatedAt: 'July 2026',
    updatedIso: '2026-07-19T00:00:00Z',
    schemaType: 'WebPage',
    summaryTitle: 'What Frame Syndicate does',
    summary: 'Frame Syndicate builds fast, accessible, search-ready digital systems that help businesses launch, rank, and scale.',
    details: 'We combine strategy, design, engineering, and search optimization so your website is useful to people, understandable to AI systems, and easy for search engines to crawl.',
    bullets: [
      'Semantic HTML5 and clean navigation',
      'Fast Vite builds with prerendered routes',
      'Accessible components and responsive layouts',
      'SEO, AEO, and GEO-friendly content structure',
    ],
    examples: [
      'Launch a new company site with clear service pages and contact paths.',
      'Improve existing visibility with better metadata, schema, and internal links.',
      'Turn service descriptions into answer-first content that can be cited by AI tools.',
    ],
    links: [
      { label: 'About us', to: '/about' },
      { label: 'Services', to: '/services' },
      { label: 'Contact', to: '/contact' },
    ],
    ctaLabel: 'Start a project',
    ctaTo: '/contact',
    faqs: [
      {
        q: 'What does Frame Syndicate specialize in?',
        a: 'We specialize in software development, cloud solutions, cybersecurity, AI, SEO, and digital strategy for growing businesses.',
      },
      {
        q: 'How do you make a site easy to understand for AI systems?',
        a: 'We use semantic HTML, clear headings, concise summaries, structured data, and entity-based content that connects services, people, and outcomes.',
      },
      {
        q: 'Do you build mobile-friendly websites?',
        a: 'Yes. Every project is designed mobile-first and validated against responsive behavior, accessibility, and performance needs.',
      },
    ],
  },
  '/about': {
    label: 'About Us',
    title: 'About Frame Syndicate | Team, Mission & Story',
    description: 'Learn about Frame Syndicate, our mission, leadership, and the team behind our technology delivery and growth-focused services.',
    author: 'Frame Syndicate editorial team',
    updatedAt: 'July 2026',
    updatedIso: '2026-07-19T00:00:00Z',
    schemaType: 'AboutPage',
    summaryTitle: 'Who Frame Syndicate is',
    summary: 'Frame Syndicate is a technology partner focused on clear delivery, measurable growth, and long-term relationships.',
    details: 'We started with a simple goal: make technology less noisy and more useful. That means shipping work that is secure, maintainable, and aligned with business goals rather than chasing buzzwords.',
    bullets: [
      'Strategy-led delivery with clear milestones',
      'Full-stack engineering and design expertise',
      'Security-first, performance-focused builds',
    ],
    examples: [
      'Helping a business modernize its web presence without losing credibility.',
      'Scaling a product team with experienced design and engineering support.',
      'Creating a sharper market story through better service positioning.',
    ],
    links: [
      { label: 'Services', to: '/services' },
      { label: 'Portfolio', to: '/portfolio' },
      { label: 'Contact', to: '/contact' },
    ],
    ctaLabel: 'Talk to the team',
    ctaTo: '/contact',
    faqs: [
      {
        q: 'What kind of clients do you work with?',
        a: 'We work with businesses that want practical digital growth, especially teams that need reliable engineering, better visibility, and faster delivery.',
      },
      {
        q: 'Where is Frame Syndicate based?',
        a: 'We are based in Jhapa, Nepal, with offices in Birtamode and Dhulabari.',
      },
      {
        q: 'What makes your team different?',
        a: 'We focus on outcomes that are easy to verify: clearer messaging, faster websites, stronger search visibility, and systems that are easier to maintain.',
      },
    ],
  },
  '/services': {
    label: 'Services',
    title: 'Frame Syndicate Services | Cloud, Software, AI & SEO',
    description: 'Explore Frame Syndicate services across cloud solutions, software development, cybersecurity, AI, data analytics, IT consulting, and SEO.',
    author: 'Frame Syndicate editorial team',
    updatedAt: 'July 2026',
    updatedIso: '2026-07-19T00:00:00Z',
    schemaType: 'Service',
    summaryTitle: 'What we deliver',
    summary: 'Our services cover the full stack of digital delivery, from architecture and code to security, analytics, and search visibility.',
    details: 'The goal is not just to build something that looks good. We build systems that load fast, answer user questions clearly, and support measurable business outcomes.',
    bullets: [
      'Cloud migration and infrastructure support',
      'Custom software and web application development',
      'Cybersecurity, audits, and hardening',
      'AI, analytics, and automation workflows',
    ],
    examples: [
      'A service page that explains the problem, the process, and the result in one place.',
      'A migration plan that preserves SEO value while improving performance.',
      'An AI-ready content structure that can be summarized cleanly by search assistants.',
    ],
    links: [
      { label: 'About us', to: '/about' },
      { label: 'Portfolio', to: '/portfolio' },
      { label: 'Contact', to: '/contact' },
    ],
    ctaLabel: 'Request a consultation',
    ctaTo: '/contact',
    faqs: [
      {
        q: 'How do I choose the right service?',
        a: 'Start with the business outcome you need. If you want better visibility, begin with SEO. If you need a new product or workflow, start with software or cloud architecture.',
      },
      {
        q: 'Do you work on existing systems?',
        a: 'Yes. We can improve, extend, or modernize existing systems without forcing a full rebuild when that is not necessary.',
      },
      {
        q: 'Do you provide ongoing support after launch?',
        a: 'Yes. We can continue with maintenance, optimization, and iterative improvements after launch.',
      },
    ],
  },
  '/portfolio': {
    label: 'Portfolio',
    title: 'Frame Syndicate Portfolio | Client Projects & Case Studies',
    description: 'Review selected work from Frame Syndicate, including cloud migrations, software platforms, AI systems, and security transformations.',
    author: 'Frame Syndicate editorial team',
    updatedAt: 'July 2026',
    updatedIso: '2026-07-19T00:00:00Z',
    schemaType: 'CollectionPage',
    summaryTitle: 'What the portfolio shows',
    summary: 'Our portfolio highlights the kind of work we ship: clear outcomes, measurable improvements, and solutions built for scale.',
    details: 'The examples are designed to show the pattern behind our work: identify the business problem, build a practical solution, and measure the result.',
    bullets: [
      'Enterprise and startup-friendly delivery',
      'Projects focused on scale, speed, and security',
      'Outcomes that support both users and search engines',
    ],
    examples: [
      'Cloud migration work for a financial services platform.',
      'Software delivery for e-commerce and startup growth.',
      'Security and AI projects built around reliability and clarity.',
    ],
    links: [
      { label: 'Services', to: '/services' },
      { label: 'About us', to: '/about' },
      { label: 'Contact', to: '/contact' },
    ],
    ctaLabel: 'Start your case study',
    ctaTo: '/contact',
    faqs: [
      {
        q: 'What kinds of projects are shown here?',
        a: 'The portfolio includes cloud, software, AI, security, and growth-focused delivery examples.',
      },
      {
        q: 'Can you build something similar for my business?',
        a: 'Yes. We can adapt the same approach to your goals, constraints, and audience.',
      },
      {
        q: 'Do you share case study details publicly?',
        a: 'We can share public summaries and keep sensitive implementation details private when needed.',
      },
    ],
  },
  '/contact': {
    label: 'Contact',
    title: 'Contact Frame Syndicate | Start Your Project',
    description: 'Contact Frame Syndicate to discuss software, cloud, cybersecurity, AI, or SEO projects and start a free consultation.',
    author: 'Frame Syndicate editorial team',
    updatedAt: 'July 2026',
    updatedIso: '2026-07-19T00:00:00Z',
    schemaType: 'ContactPage',
    summaryTitle: 'How to reach us',
    summary: 'Use the contact form, call us, or email us if you want a fast response and a clear next step for your project.',
    details: 'We normally respond quickly with a short discovery step so we can understand the goal, constraints, timeline, and the best path forward.',
    bullets: [
      'Best for new builds, redesigns, and SEO improvements',
      'Use the form to share scope, timeline, and goals',
      'Direct contact details are listed for quick follow-up',
    ],
    examples: [
      'Share your website URL and explain what is not working.',
      'Tell us the service you need and the result you want.',
      'Mention any deadline so we can set expectations early.',
    ],
    links: [
      { label: 'Services', to: '/services' },
      { label: 'Portfolio', to: '/portfolio' },
      { label: 'About us', to: '/about' },
    ],
    ctaLabel: 'Email the team',
    ctaTo: 'mailto:theframesyndicate@gmail.com',
    faqs: [
      {
        q: 'How soon do you respond?',
        a: 'We aim to respond as quickly as possible and usually start with a short discovery reply.',
      },
      {
        q: 'What should I include in my message?',
        a: 'Include your goal, current website or product link, timeline, and any technical or business constraints.',
      },
      {
        q: 'Can I contact you about SEO only?',
        a: 'Yes. We handle SEO as a standalone engagement or as part of a broader build.',
      },
    ],
  },
}
